# Mirror
RURIMA_LXC_MIRROR=mirrors.tuna.tsinghua.edu.cn/lxc-images
RURIMA_LXC_MIRROR_FALLBACK=images.linuxcontainers.org

# OS to install
# Make sure there is ${RURIMA_LXC_OS} in setup/setup.sh
RURIMA_LXC_OS=ubuntu

# OS version to install
RURIMA_LXC_OS_VERSION=oracular

# OS dir to install
# The actual directory is the `CONTAINER_DIR` in `customize.sh`
# CONTAINER_DIR=/data/${RURIMA_LXC_OS}
CONTAINER_DIR=/data/ubuntu

PASSWORD=123456
PORT=22


# ruri config

REQUIRE_SUDO=true
MOUNT_POINT=/data/media/0
MOUNT_ENTRANCE=/sdcard
MOUNT_READ_ONLY=true
UNMASK_DIRS=false
PRIVILEGED=false
RUNTIME=false
